### ISSUE TITLE
Frontend post page 

### ISSUE THREAD

**Issue by DEVANSARAVANAN** [LiveWiresSRM2023/SRM_CURIOUS_BUG_REACT#11]
frontend team need to change the post page that arise while click the create post button. please refer the flutter website.

Currently we have like:

![Screenshot (2)](https://github.com/LiveWiresSRM2023/SRM_CURIOUS_BUG_REACT/assets/121475216/9bfe8ed5-3d34-4ce4-8115-3f617d4235c0)

We need to be change like:

![Screenshot (4)](https://github.com/LiveWiresSRM2023/SRM_CURIOUS_BUG_REACT/assets/121475216/e674e8c5-11f5-4dc9-b16c-d5d1f36831f7)

Once your complete the post page. push and inform to me then only I can integrate with backend.

**Comment by seyaduraja** [comment]
yeah i'll make the changes
