### ISSUE TITLE
Google Autectication Bug

### ISSUE THREAD

**Issue by abin0001** [LiveWiresSRM2023/SRM_CURIOUS_BUG_REACT#8]
Google Authentication is not working in real time @vaseem15905 @DEVANSARAVANAN

**Comment by vaseem15905** [comment]
when the profile page gets  reloaded , couldn't authenticate the user , so ended up with the error "user is not authenticated" .

**Comment by vaseem15905** [comment]
when "auth.onAuthStateChanged()" is  used  to get , the firebase related data  , it is working  perfectly . and also we found that the firebase was initialized twice which should be initialized only once .   by addressing that , now  fixed that too  and  It it Working perfectly now! :)

**Comment by DEVANSARAVANAN** [comment]
> Google Authentication is not working in real time @vaseem15905 @DEVANSARAVANAN

Now, Its working we fixed it. It will move to home page directly after landing page, suppose user is verified it can verify automatically. If user is new to the website It will move to sign in page that will authenticate the user
